Bestquotes/Bestquotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

Bestquotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('authors/', views.authors, name='authors'),
    path('detail/<int:author_id>', views.detail, name='detail'),
    path('fill_db/', views.fill_db, name='fill_db'),
]

Bestquotes/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Bestquotes/quotesapp/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=150, unique=True, null=False)
    born_date = models.DateTimeField()
    born_location = models.CharField(max_length=150)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return f'{self.fullname}'


class Tag(models.Model):
    name = models.CharField(max_length=50)


class Quote(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.CharField(max_length=500)

    def __str__(self):
        return f'{self.quote[:50]}'

Bestquotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, SelectDateWidget
from .models import Tag, Author, Quote


class AuthorForm(ModelForm):
    fullname = CharField(max_length=150, required=True, widget=TextInput())
    born_date = DateField(widget=SelectDateWidget(years=[i for i in range(1800, 2023)]))
    born_location = CharField(max_length=150, widget=TextInput())
    description = CharField(max_length=1000, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):

    quote = CharField(min_length=5, max_length=500, required=True, widget=TextInput())
    author = CharField(min_length=1, max_length=150, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['tags', 'author']

Bestquotes/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime
import json
from pathlib import Path

from django.contrib.auth.decorators import login_required
from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Author, Quote


def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quotesapp/index.html', {"quotes": quotes})


@login_required
def fill_db(request):
    quotes = Quote.objects.all()
    with open(str(Path(__file__).resolve().parent)+'/static/quotesapp/authors.json', 'r', encoding='utf-8') as fh:
        rez = json.load(fh)
        for itr in rez:
            new_author = Author(description=itr['description'][:1000],
                                born_date=datetime.strptime(itr['born_date'], '%B %d, %Y').date(),
                                born_location=itr['born_location'], fullname=itr['fullname'])
            new_author.save()
    # tags
    with open(str(Path(__file__).resolve().parent)+'/static/quotesapp/quotes.json', 'r', encoding='utf-8') as fh:
        rez = json.load(fh)
        unique_tags = set()
        for itr in rez:
            for cur_tag in itr['tags']:
                unique_tags.add(cur_tag)
        for unique_tag in unique_tags:
            new_tag = Tag(name=unique_tag)
            new_tag.save()

        for itr in rez:
            new_quote = Quote()
            aut_id = Author.objects.get(fullname=itr['author'])
            new_quote.quote = itr['quote'][0:500]
            new_quote.author = aut_id
            new_quote.save()
            choice_tags = Tag.objects.filter(name__in=itr['tags'])
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            new_quote.save()
    return render(request, 'quotesapp/index.html', {"quotes": quotes})


def detail(request, author_id):
    author_ob = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotesapp/detail.html', {"author": author_ob})


def authors(request):
    authors = Author.objects.all()
    return render(request, 'quotesapp/authors.html', {"authors": authors})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/author.html', {'form': form})

    return render(request, 'quotesapp/author.html', {'form': AuthorForm()})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})

    return render(request, 'quotesapp/tag.html', {'form': TagForm()})


@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = Quote()
            new_quote.quote = request.POST.get('quote')
            new_quote.author = Author.objects.get(fullname=request.POST.get('author'))
            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            new_quote.save()

            quotes = Quote.objects.all()
            return render(request, 'quotesapp/index.html', {"quotes": quotes})
        else:
            return render(request, 'quotesapp/quote.html', {"tags": tags, "authors": authors, 'form': form})

    return render(request, 'quotesapp/quote.html', {"tags": tags, "authors": authors, 'form': QuoteForm()})

Bestquotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter author fullname:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter author bio:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

Bestquotes/quotesapp/templates/quotesapp/authors.html
{% extends "quotesapp/base.html" %}

{% block content %}
<h1>Authors</h1>
<div class="row">
    {% for author in authors %}
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <p class="card-text">{{author.fullname}}</p>
                <p class="card-text">{{author.born_date}}</p>
                <p class="card-text">{{author.born_location}}</p>
                <a href="{% url 'quotesapp:detail' author.id %}" class="btn btn-info">More</a>
            </div>
        </div>
    </div>

    {% endfor %}

</div>
{% endblock %}

Bestquotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quote</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>
<body>

<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
    <ul>
        <li><a href="{% url 'quotesapp:main' %}" role="button">Home</a></li>
        <li><a href="{% url 'quotesapp:authors' %}" role="button">Authors</a></li>
    </ul>
    {% if user.is_authenticated %}
    <ul>
        <li><a href="{% url 'quotesapp:quote' %}" role="button">Add quote</a></li>
        <li><a href="{% url 'quotesapp:author' %}" role="button">Add author</a></li>
        <li><a href="{% url 'quotesapp:tag' %}" role="button">Add tag</a></li>
        <li><a href="{% url 'quotesapp:fill_db' %}" role="button">Fill DB</a></li>
    </ul>
    <ul>
        <li>Welcome <b>{{ user.username }}!</b></li>
        <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
        <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
    </ul>
    {% endif %}
    </nav>
    {% block content %}



    {% endblock %}
</main>
</body>
</html>

Bestquotes/quotesapp/templates/quotesapp/detail.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h1>{{author.fullname}}</h1>
<p>Born: <kbd>{{author.born_date}}</kbd></p>
<p>Location: <b>{{author.born_location}}</b></p>
<p>Description: <b>{{author.description}}</b></p>

{% endblock %}

Bestquotes/quotesapp/templates/quotesapp/index.html
{% extends "quotesapp/base.html" %}

{% block content %}

    {% for quote in quotes %}
    <ul>
        <li>
            <p> {{ quote.quote }} </p>
        </li>
    </ul>
    {% endfor %}

{% endblock %}

Bestquotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author:
            <select name="author">
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
         </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

Bestquotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}